ELF Dump Fix
waviousllc/wav-rtos-sw pull request #29
Opened 2021-07-21 15:22 UTC by wavious-wpatty

Fixes:
  - Fixes issue where ELF dump runs prior to header patch (#27)

Features:
  - None

2021-07-24 13:47 UTC, wavious-jbasista requested changes

2021-07-24 13:47 UTC, wavious-jbasista commented on bsp/wavious-wh440/CMakeLists.txt
>  macro(bsp_post_build target)
lets change target here to TARGET to match this change in wavious-mcu and what was done in the build script as well.  Will need to adjust through the rest of the macro as well.

2021-07-24 19:09 UTC, wavious-wpatty commented
@wavious-jbasista I need to include wav-build updates in this commit too. I will do that once I release wav-build.

2021-07-28 13:30 UTC, wavious-jbasista approved these changes
Looks all good.

2021-08-05 15:47 UTC, merged